import type { SiteCopy } from "@/content/types";

export const cn: SiteCopy = {
  localeLabel: "CN",
  otherLocaleLabel: "EN",
  skip: "跳到正文",
  menuOpen: "打开菜单",
  menuClose: "关闭菜单",
  brandDescriptor: "高管寻访与人才发展",
  nav: [
    { key: "home", label: "首页" },
    { key: "search", label: "高管寻访" },
    { key: "collaboration", label: "合作" },
    { key: "talent", label: "人才发展" },
    { key: "about", label: "关于" },
    { key: "contact", label: "联系" },
  ],
  ctas: {
    discuss: "洽谈寻访项目",
    collaboration: "探讨合作",
    exploreSearch: "了解高管寻访",
    workTogether: "一起合作",
    exploreTalent: "了解人才发展",
    startConversation: "开始沟通",
    discussCollaboration: "洽谈合作方式",
    discussNeeds: "谈谈您的需求",
    contactAna: "联系 Ana",
  },
  footer: {
    rights: "© 2026 Ana Ramos-Prudhommeaux. 保留所有权利。",
    line: "NextStep Services Limited • Compass Business Consulting • OPNR Game Partner",
    privacy: "隐私",
  },
  copied: "已复制",
  contactCards: {
    email: "电子邮箱",
    linkedin: "LinkedIn",
    copyEmail: "复制邮箱",
  },
  home: {
    eyebrow: "高管寻访 • 人才发展 • 国际视角",
    headline: "面向高级与复杂岗位的高管寻访，包括领导者如何起步。",
    supporting:
      "企业和寻访公司请我来推进委托：市场、候选人、谈话。如果这个人要到另一个国家或另一种文化里落地，我可以陪过最初几个月。这套做法主要是在中国形成的，之后延伸到亚洲、拉丁美洲和欧洲。",
    credibility: [
      "超过 20 年高管寻访、领导力发展与国际商务经验",
      "在中国、亚洲、拉丁美洲和欧洲工作",
      "西班牙语与英语；法语和普通话可日常交流",
    ],
    overviewTitle: "专业概览",
    footprintLabel: "国际足迹",
    footprint: "在中国 19 年；欧洲与拉丁美洲",
    educationLabel: "教育背景",
    education: [
      { title: "EMSC 创新与创业在读", detail: "巴黎 HEC（2024–2026）" },
      { title: "战略营销研究生文凭", detail: "墨西哥 ITESO" },
      { title: "会计与金融学士", detail: "墨西哥 ITESO" },
    ],
    specialtiesLabel: "主要专长",
    specialties: "高管寻访、项目交付、人才地图、高管融入、跨文化领导力",
    languagesLabel: "语言",
    languages: "西班牙语（母语）• 英语（专业熟练）• 法语（日常交流）• 普通话（日常交流）",
    supportTitle: "我可以如何支持",
    supportNote: "多数客户从寻访开始。人才发展是在这个人必须安顿到岗位上的时候才进入。",
    services: [
      {
        key: "search",
        title: "高管寻访与项目交付",
        body: "C-level、总监和关键专业岗位：任务说明、人才地图、接触、初步评估，以及委托的交付。",
        cta: "了解高管寻访",
      },
      {
        key: "collaboration",
        title: "与高管寻访公司合作",
        body: "为寻访公司提供保密的人手：研究、地图、与候选人的谈话、评估，或在高级委托上的交付。",
        cta: "一起合作",
      },
      {
        key: "talent",
        title: "高管融入与人才发展",
        body: "决定之后：入职、跨文化领导力、教练、测评，以及与团队的工作。",
        cta: "了解人才发展",
      },
    ],
    credentialsTitle: "专业认证",
    practiceTitle: "人才决策影响经营结果。",
    practice: [
      "合适的任命可以推动业务。不合适的任命会带来可避免的成本、干扰和势头损失。我以寻访经验、市场判断、候选人评估和跨文化视角，支持组织与寻访公司完成高级、复杂的项目。",
      "这份工作靠审慎和判断。委托需要时，我可以从短名单陪到最初几个月。",
    ],
    calloutTitle: "从任命到顺利起步",
    callout:
      "寻访和到任起步是同一件事。我把聘用决定和最初几个月连在一起：领导者必须和谁对齐，文化会对他提出什么要求。",
    tabs: [
      {
        id: "approach",
        label: "为何与 Ana 合作",
        title: "寻访专业，加上更完整的人才视角",
        items: [
          { title: "国际寻访视角", body: "来自在中国、亚洲、拉丁美洲和欧洲的长期经验。" },
          { title: "高级岗位寻访经验", body: "覆盖工业、制造、汽车、物流、供应链、快消与国际业务环境。" },
          { title: "录用之后", body: "过渡对领导者的要求：文化，以及他要加入的团队。" },
          { title: "灵活的合作方式", body: "作为独立顾问，或作为高管寻访团队的协作延伸。" },
          { title: "专业审慎", body: "尊重保密、竞业与不挖角约定，以及客户特定流程。" },
        ],
      },
      {
        id: "search",
        label: "高管寻访",
        title: "一个寻访项目可以包括",
        items: [
          { title: "C-level、总监与高级职能领导岗位", body: "复杂、保密、难招的项目，包含寻访策略与岗位校准。" },
          { title: "地图、研究与接触", body: "人才地图、市场情报、候选人识别，以及审慎的接触方式。" },
          { title: "评估与到任", body: "初步评估、面试支持，以及在需要时的入职与融入。" },
        ],
      },
      {
        id: "talent",
        label: "人才发展",
        title: "聘用决定之后的选择性支持",
        items: [
          { title: "高管融入与入职", body: "面向进入新岗位、新市场或新组织文化的领导者。" },
          { title: "跨文化教练与测评", body: "为跨文化工作的领导者提供个别教练，以及面向发展的测评对话。" },
          { title: "团队与工作坊", body: "引导式对齐、领导力工作坊，以及按业务需要确定的学习重点。" },
        ],
      },
    ],
    timelineTitle: "超过 20 年积累的专业能力",
    timeline: [
      {
        role: "联合创始人、高管顾问与引导师",
        dates: "2016 – 至今",
        place: "NextStep Services Limited • 中国上海与墨西哥",
        body: "独立顾问工作涵盖高管寻访、人才发展与国际领导力情境。为组织与寻访伙伴提供高级项目、融入与引导式学习支持。",
      },
      {
        role: "合作合伙人",
        dates: "2025 – 至今",
        place: "OPNRGame • 香港与拉美",
        body: "以合作合伙人的身份，做信任与跨团队领导力的工作，形式是基于神经科学的游戏化企业学习。",
      },
      {
        role: "创始人兼董事",
        dates: "2014 – 2023",
        place: "Compass Business Consulting • 中国与亚洲",
        body: "为在亚太开展业务的跨国公司做委托寻访、领导力引导和高管融入。",
      },
      {
        role: "董事总经理 – 上海办公室",
        dates: "2004 – 2013",
        place: "AIMS International – Human Capital Partners China",
        body: "在上海办公室负责高管寻访。大中华区工业、物流、制造和快消行业的 C-level 与总监级安置。",
      },
    ],
    sectorsTitle: "复杂商业环境中的经验",
    sectors:
      "我支持过工业、制造、汽车、物流、供应链、快消与国际增长环境中的领导力与人才项目。我与墨西哥、拉丁美洲及跨境情境中的组织和合作伙伴公司共事。",
    closingTitle: "正在寻找高级人才，或需要有经验的寻访支持？",
    closing: "我们可以谈谈项目、市场背景，以及哪一种支持最有价值。",
    based: "常驻墨西哥瓜达拉哈拉 • 与国际客户合作。",
  },
  search: {
    eyebrow: "主要业务",
    title: "高管寻访与项目交付",
    lede: "为高级、复杂、对业务至关重要的招聘提供直接参与的支持。",
    intro:
      "高级寻访从业务问题出发，然后才是市场，以及谁有可能做成这个岗位。我为企业，也为寻访伙伴推进这个过程，并且可以留下来，处理新领导者要站得住所需要的事。",
    supportTitle: "我支持的工作",
    support: [
      "C-level、总监与高级职能领导岗位寻访",
      "复杂、保密、难招的项目",
      "寻访策略与岗位校准",
      "人才地图与市场情报",
      "候选人识别、研究与接触",
      "初步评估与面试支持",
      "跨境与多元文化寻访",
      "在需要时提供高管入职与融入支持",
    ],
    methodTitle: "结构化、协作式的做法",
    steps: [
      { title: "澄清业务需要", body: "我们一起界定岗位、委托范围、成功标准、组织背景和寻访参数。" },
      { title: "绘制市场", body: "我识别相关人才池、目标机构，以及需要考虑的市场因素。" },
      { title: "审慎接触候选人", body: "我以专业、保密的方式接触潜在候选人，并清楚说明机会本身。" },
      { title: "判断匹配", body: "我看相关经验、这个人如何带人、他要从这个岗位得到什么，以及这种文化是不是他进得去的。" },
      { title: "支持过渡", body: "在有帮助时，我可以提供测评、入职或融入支持，为顺利起步创造条件。" },
    ],
    environments:
      "我的背景包括工业、制造、汽车、物流、供应链、快消与国际业务中的高管与领导力项目。在需要跨境协调、本地市场判断和高级利益相关方管理的环境中，我尤其自如。",
    ctaTitle: "洽谈一个寻访项目",
    ctaBody: "请说明岗位、地点、业务背景，以及您需要的支持程度。我会回复，并判断自己是否适合这项委托。",
  },
  collaboration: {
    eyebrow: "面向高管寻访公司",
    title: "高管寻访交付的有经验合作伙伴",
    lede: "为从事高级、复杂或国际项目的寻访公司，提供灵活、保密的支持。",
    intro:
      "我和需要额外人手、本地或跨文化判断，或需要一位资深的人接手委托一部分的寻访公司合作。我在国际市场带过寻访。审慎没有商量余地，节奏必须是客户能感觉到的节奏。",
    supportTitle: "合作支持",
    support: [
      "目标公司研究与人才地图",
      "候选人识别与长名单",
      "候选人接触与沟通",
      "市场情报与本地市场视角",
      "初步面试与评估支持",
      "项目协调与寻访交付支持",
      "墨西哥、拉丁美洲与跨境项目支持",
      "当与委托相关时，提供高管融入、测评或跨文化支持",
    ],
    principlesTitle: "工作原则",
    principles: [
      "保密与专业审慎",
      "尊重不挖角协议和项目特定流程",
      "沟通清楚、响应及时、交付物明确",
      "以客户为先，保护合作寻访公司的关系与品牌",
      "支持方式灵活：从一段明确的研究工作，到委托里更大的一块",
    ],
    ctaTitle: "探讨合作",
    ctaBody: "如果您正在进行或即将开始一个项目，并需要有经验的支持，我很乐意讨论背景、范围与合作方式。",
  },
  talent: {
    eyebrow: "互补业务",
    title: "高管融入与人才发展",
    lede: "有重点的发展支持，帮助领导者与团队在变化或多元文化环境中建立对齐、能力与信心。",
    intro:
      "聘书签了之后，这次任命还得站得住。最初几个月决定其中很大一部分：关系，以及这个人能不能读懂文化。聘用之后我会接这项工作，客户或学习伙伴带来合适的委托时，我也会接。",
    areasTitle: "支持范围",
    services: [
      {
        title: "高管融入与入职",
        body: "支持进入新岗位、新市场或新组织文化的领导者，关注利益相关方对齐、文化情境和早期影响重点。",
      },
      {
        title: "跨文化教练",
        body: "为跨文化工作、国际调动、管理多元文化利益相关方，或需要调整领导方式的领导者提供个别教练。",
      },
      {
        title: "测评",
        body: "面向发展的测评支持，用于建立自我觉察、识别领导力重点，并为有针对性的发展对话提供依据。",
      },
      {
        title: "团队教练与对齐",
        body: "与领导团队进行引导式工作，澄清优先事项，加强沟通，改善信任，并建立有效的协作方式。",
      },
      {
        title: "领导力与软技能工作坊",
        body: "关于领导力、沟通、协作、文化智力及相关人员能力的实践型、互动式学习。",
      },
      {
        title: "学习需求评估",
        body: "帮助识别发展需要、确定学习重点，并为领导者或团队设计相关项目。",
      },
    ],
    engagementTitle: "合作如何进行",
    engagement:
      "我按组织的需要来定这项工作。我可以直接与客户合作，也可以通过可信的学习伙伴，以合作引导师、教练或顾问的身份参与。",
    ctaTitle: "探讨人才发展支持",
  },
  about: {
    eyebrow: "专业背景",
    title: "关于 Ana Ramos-Prudhommeaux",
    lede: "高管寻访与领导力工作，来自二十多年的国际委托。",
    intro: [
      "我是独立顾问。寻访是这套执业的核心。领导力发展放在旁边。这些年是在中国度过的，之后在亚洲、拉丁美洲和欧洲。",
      "我在大中华区带过高管寻访，随后为亚洲的跨国公司创办了一家咨询机构。今天我接寻访委托、教练和引导式学习，也包括通过少数合作网络，当一家组织面对增长、一次变化，或一次跨境招聘。",
    ],
    snapshotTitle: "经历摘要",
    snapshot: [
      "在大中华区领导并交付高管寻访，包括 C-level 与总监级项目。",
      "创立并领导一家咨询机构，为亚太跨国公司提供高管寻访、领导力引导与高管融入。",
      "目前的独立顾问工作涵盖高管寻访、人才发展与国际领导力情境。",
      "作为培训师、教练和引导师，与全球人才发展及学习伙伴合作。",
    ],
    expertiseTitle: "专业领域",
    expertise: [
      "高管寻访与复杂岗位交付",
      "人才地图、研究与候选人评估",
      "高管入职与领导力融入",
      "跨文化领导力与跨文化协作",
      "高管教练、团队教练与引导",
      "领导力、沟通与软技能发展",
    ],
    internationalTitle: "国际视角",
    international:
      "我在中国生活和工作了很多年，现在仍在多个市场工作。文化会改变人如何建立信任、如何做决定、如何把一位新领导者接进来。这一点在寻访里要紧，在最初几个月里又要紧一次，尤其是公司跨境运作的时候。",
    ctaTitle: "谈谈我可以如何帮忙",
  },
  contact: {
    eyebrow: "合作与联系",
    title: "先从业务背景说起。",
    lede: "无论您在做高级寻访、需要有人推进委托，还是在看人才发展，请留几项信息。我会亲自、保密地回复。",
    fields: {
      name: "姓名",
      company: "公司",
      email: "电子邮箱",
      location: "国家 / 所在地",
      inquiry: "咨询类型",
      description: "需求简述",
      timing: "期望时间",
      consent: "我理解本次咨询将被保密处理。",
    },
    inquiryOptions: [
      { value: "search", label: "高管寻访" },
      { value: "collaboration", label: "与寻访公司合作" },
      { value: "talent", label: "人才发展" },
      { value: "other", label: "其他" },
    ],
    placeholders: {
      name: "您的姓名",
      company: "公司或寻访机构",
      email: "name@company.com",
      location: "城市，国家",
      description: "岗位、市场，以及您需要的支持。",
      timing: "本月、下个季度，或时间灵活",
    },
    submit: "发送咨询",
    sending: "发送中…",
    required: "必填",
    errors: {
      name: "请填写姓名。",
      company: "请填写公司或机构。",
      email: "请填写有效的电子邮箱。",
      location: "请填写国家或城市。",
      inquiry: "请选择咨询类型。",
      description: "请用几句话说明需求。",
      consent: "请确认保密说明后再继续。",
      generic: "咨询未能确认。请重试，或直接发邮件。",
    },
    successTitle: "您的咨询已发送。",
    successBody: "Ana 会阅读并亲自回复。",
    successDirect: "写信给 Ana",
    another: "再发送一条咨询",
  },
  privacy: {
    title: "隐私",
    lede: "本网站如何处理您选择提交的信息。",
    sections: [
      {
        heading: "谁会收到咨询",
        body: "Ana Ramos-Prudhommeaux 是常驻墨西哥瓜达拉哈拉的独立顾问。表单咨询会发送至 ana.ramos.cn@gmail.com。",
      },
      {
        heading: "表单会询问什么",
        body: "姓名、公司、电子邮箱、国家或所在地、咨询类型、需求简述、期望时间，以及您确认咨询将被保密处理。",
      },
      {
        heading: "如何使用",
        body: "用于阅读并回复您的请求。这些信息不会被出售，也不会用于广告名单。",
      },
      {
        heading: "如何联系 Ana",
        body: "表单会把您的信息发送到 ana.ramos.cn@gmail.com，以便 Ana 回复。您也可以直接写信到这个地址。",
      },
      {
        heading: "Cookie 与链接",
        body: "本网站不设置广告或分析 Cookie。LinkedIn 是独立服务，有其自己的隐私政策。",
      },
    ],
  },
  seo: {
    home: {
      title: "Ana Ramos | 高管寻访与人才发展顾问",
      description: "为墨西哥、拉丁美洲及国际市场的组织与寻访公司，提供高管寻访、人才地图与领导力融入支持。",
    },
    search: {
      title: "高管寻访顾问 | Ana Ramos",
      description: "支持高级与复杂寻访：项目交付、人才地图、候选人研究、接触与评估。",
    },
    collaboration: {
      title: "高管寻访研究与交付支持 | Ana Ramos",
      description: "为高管寻访公司和复杂项目提供保密研究、地图、候选人接触与交付支持。",
    },
    talent: {
      title: "高管融入与人才发展 | Ana Ramos",
      description: "为国际组织提供高管入职、跨文化教练、测评、团队对齐与领导力工作坊。",
    },
    about: {
      title: "关于 Ana Ramos-Prudhommeaux | 高管寻访顾问",
      description: "了解 Ana Ramos-Prudhommeaux：国际高管寻访、领导力发展与跨文化咨询经验。",
    },
    contact: {
      title: "联系 Ana Ramos | 高管寻访与人才发展",
      description: "联系 Ana Ramos，洽谈高管寻访项目、寻访公司合作或人才发展需求。",
    },
  },
  notFound: {
    title: "这个页面不在网站上。",
    body: "地址可能已更改。下方是业务页面的链接。",
    home: "返回首页",
  },
  error: {
    title: "这个页面没有载入。",
    body: "请刷新页面。如果再次出现，请直接发邮件。",
    retry: "再试一次",
  },
};
